---
- name: Install fedora copr plugin (dnf)
  ansible.builtin.package:
    name: dnf-command(copr)
    state: present

- name: Enable caddy repo
  ansible.builtin.command: dnf copr enable -y @caddy/caddy
  args:
    warn: false
  register: dnf_repo_enable
  changed_when: false

- name: Install caddy package
  ansible.builtin.dnf:
    name: caddy
    state: present
